"""
Modulo de configuracoes
"""

from .settings import (
    DocumentCategory,
    TIPOS_LAUDO,
    TIPOS_RECEITA,
    TIPOS_SAUDE_MENTAL,
    ALLOWED_FILE_TYPES,
    IMAGE_MIME_TYPES,
    CLAUDE_MODEL,
    MAX_TOKENS,
    TEMPERATURE,
    CACHE_ENABLED,
    CACHE_TTL_SECONDS,
    CACHE_MAX_SIZE,
    MAX_TEXT_LENGTH,
    MAX_REQUESTS_PER_SESSION,
    FREE_TRANSLATIONS_LIMIT
)

__all__ = [
    'DocumentCategory',
    'TIPOS_LAUDO',
    'TIPOS_RECEITA',
    'TIPOS_SAUDE_MENTAL',
    'ALLOWED_FILE_TYPES',
    'IMAGE_MIME_TYPES',
    'CLAUDE_MODEL',
    'MAX_TOKENS',
    'TEMPERATURE',
    'CACHE_ENABLED',
    'CACHE_TTL_SECONDS',
    'CACHE_MAX_SIZE',
    'MAX_TEXT_LENGTH',
    'MAX_REQUESTS_PER_SESSION',
    'FREE_TRANSLATIONS_LIMIT'
]
